# Generated by Django 4.2 on 2024-02-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads_scraper', '0002_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='name',
        ),
    ]
